# Generated by Django 4.2.1 on 2023-08-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=30, verbose_name='Tagy')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagy',
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_zanru', models.CharField(max_length=80, verbose_name='Žánr')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název Filmu')),
                ('rezie', models.CharField(max_length=180, verbose_name='Režie')),
                ('tagy', models.ManyToManyField(to='moviebook.tag')),
                ('zanr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='moviebook.zanr', verbose_name='Žánr')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmy',
            },
        ),
    ]
